name: Deploy Angular Project to GitHub Pages

on:
  push:
    branches:
      - main  # 或者你使用的是 main 分支

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.15'  # 指定 Node.js 版本

    - name: Install pnpm
      run: node install -g pnpm@9.4.0

    - name: Install dependencies
      run: pnpm install

    - name: Build Angular project
      run: pnpm run build --output-path docs --base-href /<repository-name>/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
